### ISSUE TITLE
Request different output for vb.net

### ISSUE THREAD

**Issue by mrkiller2010** [frk1/hazedumper#6]
I'd love a output but with this style instead, for vb.net

```

    Public oViewAngles As Integer = &H4D0C
    Public oVecPunch As Integer = &H301C
    Public oLocalPlayer As Integer = &HAA38E4
    Public oEntityList As Integer = &H4AC5E94
```

**Comment by Ar1i** [comment]
Simple workaround with PHP

`<?php
$content = file_get_contents('https://github.com/frk1/hazedumper/blob/master/csgo.hpp');
$content = str_replace('0x', '&H', $content);
echo $content;
?>`

**Comment by ReactiioN1337** [comment]
You can simply convert it with a script like that one from ari. I can't understand why someone would like to write a cheat in VB.net

**Comment by frk1** [comment]
I would recommend parsing the json and printing it into the format you need. Parsing .hpp files can be tricky, json is idiot proof.

**Comment by ReactiioN1337** [comment]
Added ;)

https://github.com/frk1/hazedumper/commit/cb49648739a0d6475a3f31a35221f946a631dbd1
https://github.com/frk1/hazedumper/commit/fa83c531481ed424e8d82d04670da5dade7b0761
