### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Happison** [frk1/hazedumper#7]
I'd like to see those added to your dumper
m_szArmsModel
m_PlayerFog
m_ClientCMD
Thanks in advance

**Comment by ReactiioN1337** [comment]
Feel free to create a pull request

**Comment by Happison** [comment]
tbh I have no idea how that works

**Comment by Ar1i** [comment]
Post sigs

**Comment by Happison** [comment]
m_szArmsModel and m_PlayerFog are netvars and for ClientCMD I found this:
ExecuteClientCmd ( VTable Function of IVEngineClient ) : 0xD3F9E
1. C4 08 E8 ? ? ? ? 5D ) - 1E
2. C4 08 E8 ?? ?? ?? ?? 5D ) - 1E
3. 0xC4, 0x08, 0xE8, 0x00, 0x00, 0x00, 0x00, 0x5D ) - 1E
4. \xC4\x08\xE8\x00\x00\x00\x00\x5D ) - 1E : xxx????x

Source : http://img.marcel-kirchhoff.de/3380158c-44b7-46db-a39b-78da4414b22f.txt

**Comment by mrkiller2010** [comment]
Also add 
    Public oDormant As Integer = &HE9
    Public bSendPacket As Integer = &HE424A
    Public m_iItemIDLow As Integer = &H2FA4

Couldn't find the signature for these :S

**Comment by ReactiioN1337** [comment]
@mrkiller2010 bSendPackets is in our repository.. At least I posted also a thread on Unknowncheats about reversing CL_Move.

https://github.com/frk1/hazedumper/blob/master/csgo.vb#L96

Dormant is since the beta of CS:GO E9 so we won't sigscan it.

**Comment by frk1** [comment]
Feel free to open a pull request.
